# Generated by Django 4.0.4 on 2022-05-18 13:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=30, unique=True, verbose_name='标题')),
                ('create_user', models.CharField(max_length=30, verbose_name='创建者')),
                ('des', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='使用描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '帮助文档',
                'verbose_name_plural': '帮助文档',
            },
        ),
    ]
