# Generated by Django 4.0.4 on 2022-05-19 11:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=100, unique=True, verbose_name='网站名称')),
                ('href', models.TextField(verbose_name='友情链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加事件')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='姓名')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('des', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '在线留言',
                'verbose_name_plural': '在线留言',
            },
        ),
        migrations.DeleteModel(
            name='Help',
        ),
    ]
