# Generated by Django 4.0.4 on 2022-05-18 13:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, unique=True, verbose_name='类型名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '事件类型',
                'verbose_name_plural': '事件类型',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=30, unique=True, verbose_name='信息名称')),
                ('create_user', models.CharField(max_length=30, verbose_name='发布部门')),
                ('status', models.CharField(choices=[('1', '未读'), ('2', '代办'), ('3', '办理中'), ('4', '已办理')], max_length=1, verbose_name='类型状态')),
                ('des', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='信息详情')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '信息管理',
                'verbose_name_plural': '信息管理',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, unique=True, verbose_name='事件名称')),
                ('befor_event_name', models.CharField(max_length=30, null=True, verbose_name='事件前件')),
                ('keyword', models.CharField(max_length=30, null=True, verbose_name='关键词')),
                ('people_number', models.IntegerField(default=0, verbose_name='受灾人数')),
                ('die_number', models.IntegerField(default=0, verbose_name='死亡人数')),
                ('hurt_number', models.IntegerField(default=0, verbose_name='受伤人数')),
                ('level', models.IntegerField(default=1, verbose_name='事故级别')),
                ('event_desc', models.TextField(null=True, verbose_name='事件描述')),
                ('processing_results', models.TextField(null=True, verbose_name='处理结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('event_type', models.ManyToManyField(to='emergency_management.eventtype', verbose_name='事件类型')),
            ],
            options={
                'verbose_name': '突发事件管理',
                'verbose_name_plural': '突发事件管理',
            },
        ),
    ]
