# Generated by Django 4.0.4 on 2022-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('1', '未读'), ('2', '代办'), ('3', '办理中'), ('4', '已办理')], default='1', max_length=1, verbose_name='类型状态'),
        ),
    ]
