# Generated by Django 4.0.4 on 2022-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_management', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': '信息提取', 'verbose_name_plural': '信息提取'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '信息接收', 'verbose_name_plural': '信息接收'},
        ),
        migrations.AddField(
            model_name='events',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True, default='2022-05-19 11:50:00', verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='befor_event_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='事件前件'),
        ),
        migrations.AlterField(
            model_name='message',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
