# Generated by Django 4.0.4 on 2022-05-19 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_management', '0003_alter_events_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='open_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 51, 56, 544788), verbose_name='发布时间'),
        ),
    ]
