# Generated by Django 4.0.4 on 2022-05-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_management', '0004_alter_events_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
